import type { Student, Post, CampusEvent } from "@/types";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "s1",
    name: "Aisha Patel",
    homeUniversity: "MIT",
    track: "Data Science",
    bio: "Python enthusiast and machine learning nerd. Here to connect with fellow data lovers and maybe start a weekend hackathon team!",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha&backgroundColor=b6e3f4`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: null,
  },
  {
    id: "s2",
    name: "Marcus Thompson",
    homeUniversity: "Stanford University",
    track: "Innovation & Entrepreneurship",
    bio: "Serial idea generator. Currently obsessed with sustainable tech startups. Love long runs and longer coffee conversations.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus&backgroundColor=c0aede`,
    linkedin: "https://linkedin.com",
    github: null,
    instagram: "https://instagram.com",
  },
  {
    id: "s3",
    name: "Sophie Laurent",
    homeUniversity: "Sciences Po Paris",
    track: "Literature & Creative Writing",
    bio: "Poet by night, prose writer by morning. Looking for a writing partner to swap drafts and offer ruthless feedback.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie&backgroundColor=ffd5dc`,
    linkedin: null,
    github: null,
    instagram: "https://instagram.com",
  },
  {
    id: "s4",
    name: "Kenji Nakamura",
    homeUniversity: "University of Tokyo",
    track: "Data Science",
    bio: "Robotics + AI intersection explorer. Can explain gradient descent with chopsticks. Looking for study partners in stats.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Kenji&backgroundColor=d1f4e0`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: null,
  },
  {
    id: "s5",
    name: "Zara Ibrahim",
    homeUniversity: "University of Cape Town",
    track: "Innovation & Entrepreneurship",
    bio: "Building fintech solutions for underbanked communities back home. Passionate about impact investing and social entrepreneurship.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Zara&backgroundColor=ffdfbf`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: "https://instagram.com",
  },
  {
    id: "s6",
    name: "Liam O'Brien",
    homeUniversity: "Trinity College Dublin",
    track: "Literature & Creative Writing",
    bio: "Aspiring novelist who also happens to write code. Interested in digital storytelling and interactive fiction.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Liam&backgroundColor=b6e3f4`,
    linkedin: null,
    github: "https://github.com",
    instagram: "https://instagram.com",
  },
  {
    id: "s7",
    name: "Priya Sharma",
    homeUniversity: "IIT Bombay",
    track: "Data Science",
    bio: "NLP researcher focused on low-resource languages. Here to learn, collaborate, and explore Boston's food scene.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=c0aede`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: null,
  },
  {
    id: "s8",
    name: "Carlos Mendoza",
    homeUniversity: "UNAM Mexico",
    track: "Innovation & Entrepreneurship",
    bio: "Turning ideas into MVPs at record speed. Firm believer that the best businesses solve real problems. Let's brainstorm!",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos&backgroundColor=ffd5dc`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: "https://instagram.com",
  },
  {
    id: "s9",
    name: "Amara Diallo",
    homeUniversity: "Cheikh Anta Diop University",
    track: "Literature & Creative Writing",
    bio: "Translating African oral traditions into contemporary fiction. My stories live between two worlds — and I like it that way.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Amara&backgroundColor=d1f4e0`,
    linkedin: "https://linkedin.com",
    github: null,
    instagram: "https://instagram.com",
  },
  {
    id: "s10",
    name: "Noah Fischer",
    homeUniversity: "ETH Zurich",
    track: "Data Science",
    bio: "Quantum computing meets classical ML — that's my research playground. Also makes surprisingly good espresso.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Noah&backgroundColor=ffdfbf`,
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    instagram: null,
  },
  {
    id: "s11",
    name: "Yuki Chen",
    homeUniversity: "Peking University",
    track: "Innovation & Entrepreneurship",
    bio: "Cross-border e-commerce nerd. Currently exploring how GenAI is reshaping retail. Open to all coffee chats!",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki&backgroundColor=b6e3f4`,
    linkedin: "https://linkedin.com",
    github: null,
    instagram: "https://instagram.com",
  },
  {
    id: "s12",
    name: "Elena Volkov",
    homeUniversity: "HSE Moscow",
    track: "Literature & Creative Writing",
    bio: "Comparative lit PhD candidate exploring speculative fiction across cultures. Big fan of Ursula Le Guin and strong tea.",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=Elena&backgroundColor=c0aede`,
    linkedin: "https://linkedin.com",
    github: null,
    instagram: "https://instagram.com",
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    authorId: "s1",
    authorName: "Aisha Patel",
    authorTrack: "Data Science",
    authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha&backgroundColor=b6e3f4`,
    tag: "StudyGroups",
    content:
      "Anyone want to form a study group for the ML module? I'm thinking Tuesday and Thursday evenings in the library. DM me or comment below!",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    likes: 14,
    likedBy: [],
    comments: [
      {
        id: "c1",
        authorName: "Kenji Nakamura",
        content: "Count me in! Tuesdays work perfectly for me.",
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
      {
        id: "c2",
        authorName: "Priya Sharma",
        content: "Yes! I can bring my notes from the NLP lecture too.",
        timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      },
    ],
  },
  {
    id: "p2",
    authorId: "s2",
    authorName: "Marcus Thompson",
    authorTrack: "Innovation & Entrepreneurship",
    authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus&backgroundColor=c0aede`,
    tag: "General",
    content:
      "Just had the most inspiring guest lecture from a Series B founder who built her company from a dorm room. The energy in that room was electric. Summer school is already exceeding expectations!",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    likes: 32,
    likedBy: [],
    comments: [
      {
        id: "c3",
        authorName: "Zara Ibrahim",
        content: "She was incredible! Her approach to customer discovery was a game changer.",
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      },
    ],
  },
  {
    id: "p3",
    authorId: "s6",
    authorName: "Liam O'Brien",
    authorTrack: "Literature & Creative Writing",
    authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=Liam&backgroundColor=b6e3f4`,
    tag: "Housing",
    content:
      "Heads up for anyone in Ashford Hall — the hot water situation on floor 3 is STILL not fixed. I've submitted a maintenance ticket (#4892). If you're also affected, please reference that ticket when you contact housing!",
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    likes: 21,
    likedBy: [],
    comments: [],
  },
  {
    id: "p4",
    authorId: "s8",
    authorName: "Carlos Mendoza",
    authorTrack: "Innovation & Entrepreneurship",
    authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos&backgroundColor=ffd5dc`,
    tag: "RideSharing",
    content:
      "Heading to Logan Airport this Saturday at 11am. Have room for 2 more! I'm happy to split an Uber. Drop your dorm below if you want to coordinate pickup.",
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    likes: 7,
    likedBy: [],
    comments: [
      {
        id: "c4",
        authorName: "Sophie Laurent",
        content: "I'd love that! I'm in Whitman Hall — can you swing by?",
        timestamp: new Date(Date.now() - 1000 * 60 * 250).toISOString(),
      },
    ],
  },
  {
    id: "p5",
    authorId: "s9",
    authorName: "Amara Diallo",
    authorTrack: "Literature & Creative Writing",
    authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=Amara&backgroundColor=d1f4e0`,
    tag: "General",
    content:
      "Quick recommendation: the bookshop on Newbury Street has a sale on contemporary African literature right now. Found three books I've been hunting for months. Definitely worth the 20-minute walk!",
    timestamp: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    likes: 18,
    likedBy: [],
    comments: [],
  },
];

export const MOCK_EVENTS: CampusEvent[] = [
  {
    id: "e1",
    title: "Opening Ceremony & Welcome Reception",
    date: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    location: "Kresge Auditorium",
    description:
      "Kick off the summer with a welcome ceremony featuring keynote remarks from the Program Director, followed by a reception with food, drinks, and mingling. All students and faculty welcome.",
    isOfficial: true,
    rsvps: { going: 87, maybe: 24, cantGo: 5 },
    userRsvp: null,
  },
  {
    id: "e2",
    title: "Industry Panel: The Future of AI in the Workplace",
    date: new Date(Date.now() + 1000 * 60 * 60 * 26).toISOString(),
    location: "Media Lab, Room 115",
    description:
      "A curated panel featuring leaders from Google, OpenAI, and two high-growth startups discussing how AI is reshaping careers across every industry. Q&A to follow.",
    isOfficial: true,
    rsvps: { going: 62, maybe: 31, cantGo: 3 },
    userRsvp: null,
  },
  {
    id: "e3",
    title: "Rooftop Sunset Hangout",
    date: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    location: "Baker House Rooftop",
    description:
      "Casual sunset hangout organized by students. Bring snacks, a blanket, and good vibes. BYOB for those of legal age. Perfect way to unwind midweek!",
    isOfficial: false,
    rsvps: { going: 23, maybe: 14, cantGo: 2 },
    userRsvp: null,
  },
  {
    id: "e4",
    title: "Workshop: Pitch Your Startup in 90 Seconds",
    date: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    location: "Sloan School, E62-223",
    description:
      "An intensive hands-on workshop for entrepreneurship track students. You'll develop, refine, and deliver a compelling 90-second pitch, with expert feedback from VCs and founders.",
    isOfficial: true,
    rsvps: { going: 44, maybe: 18, cantGo: 6 },
    userRsvp: null,
  },
  {
    id: "e5",
    title: "Data Science Hackathon: 12-Hour Sprint",
    date: new Date(Date.now() + 1000 * 60 * 60 * 96).toISOString(),
    location: "Stata Center, Building 32",
    description:
      "A 12-hour sprint where teams tackle a real-world dataset provided by a partner company. Prizes for top 3 teams. Dinner provided. Bring your laptop, your team, and your best model.",
    isOfficial: true,
    rsvps: { going: 56, maybe: 22, cantGo: 8 },
    userRsvp: null,
  },
  {
    id: "e6",
    title: "Literary Open Mic Night",
    date: new Date(Date.now() + 1000 * 60 * 60 * 120).toISOString(),
    location: "The Coop Café, Cambridge",
    description:
      "Student-organized open mic for poetry, short fiction, and creative nonfiction. Sign-up sheet will be posted at noon on the day. All genres and styles welcome!",
    isOfficial: false,
    rsvps: { going: 31, maybe: 17, cantGo: 4 },
    userRsvp: null,
  },
  {
    id: "e7",
    title: "Career Fair: Summer Program Edition",
    date: new Date(Date.now() + 1000 * 60 * 60 * 168).toISOString(),
    location: "Johnson Athletic Center",
    description:
      "20+ companies will be on campus for a dedicated career fair for summer program students. Bring copies of your resume and dress to impress. Internship and full-time opportunities available.",
    isOfficial: true,
    rsvps: { going: 93, maybe: 38, cantGo: 2 },
    userRsvp: null,
  },
];
